### ISSUE TITLE
Building crashes on "Building routes manifest file"

### ISSUE THREAD

**Issue by FullStack0verfl0w** [Lomray-Software/vite-ssr-boost#10]
**Describe the bug**
I have created an empty project and added ssr-boost there, but when building it crashes on `Building routes manifest file...` with no errors, except `Before starting the server, you need to create a build: ssr-boost build`
Development server and [this template](https://github.com/Lomray-Software/vite-template) seem to be working fine.

**To Reproduce**
1. Clone [this repository](https://github.com/FullStack0verfl0w/vite-ssr-boost-template)
2. `npm i`
3. `npm run build`
4. Build crashed with no errors.

**Additional Info**
 - OS: MacOS 14.2.1
 - Node: 20.8.1
 - Vite: 5.0.11
 - SSR Boost: 2.0.3

**Comment by MatthewPattell** [comment]
@FullStack0verfl0w thanks for reporting. Try `2.1.0` version. Also as I can see, you changed `outDir` and in this case use follow commands (or change outDir to default `../build`):
```
    "start:ssr": "ssr-boost start --build-dir dist",
    "start:spa": "ssr-boost start --only-client --build-dir dist",
    "preview": "ssr-boost preview --build-dir dist"
```

**Comment by FullStack0verfl0w** [comment]
@MatthewPattell Now it works. Thank you.
