### ISSUE TITLE
Add support for JSX

### ISSUE THREAD

**Issue by pniby** [Lomray-Software/vite-ssr-boost#12]
We're using JSX . Can you add option for JSX support?

**Comment by MatthewPattell** [comment]
@pniby Hi. What do you mean? Can you show some example?

**Comment by pniby** [comment]
In our project, we are not using typescript. Is there any option to implement it without typescript?

**Comment by MatthewPattell** [comment]
Certainly. This library has no control over this. This is basically VITE and you should take a look at their documentation.
Also you can just create `.js` and `.jsx` files instead `.ts` or `.tsx` it should works out of box.

**Comment by pniby** [comment]
Got this error 
`@lomray/vite-ssr-boost-make-aliases: tsconfig not exist in "tsconfig.json`
package.json

> {
  "name": "xxx",
  "private": true,
  "version": "0.0.0",
  "type": "module",
  "scripts": {
    "dev": "vite",
    "build:production": "vite build --mode production",
    "lint": "eslint . --ext js,jsx --report-unused-disable-directives --max-warnings 0",
    "develop": "ssr-boost dev",
    "build": "ssr-boost build",
    "start:ssr": "ssr-boost start",
    "start:spa": "ssr-boost start --only-client",
    "preview": "ssr-boost preview"
  },
  "dependencies": {
    "@lomray/vite-ssr-boost": "^2.3.1",
    "animate.css": "^4.1.1",
    "axios": "^1.6.5",
    "bootstrap": "^5.3.2",
    "framer-motion": "^10.16.5",
    "html-react-parser": "^4.2.2",
    "intersection-observer": "^0.12.2",
    "random-key": "^0.3.2",
    "react": "^18.2.0",
    "react-animation-on-scroll": "^5.1.0",
    "react-bootstrap": "^2.9.0",
    "react-countup": "^6.4.2",
    "react-dom": "^18.2.0",
    "react-error-boundary": "^4.0.11",
    "react-helmet": "^6.1.0",
    "react-helmet-async": "^1.3.0",
    "react-hook-inview": "^4.5.0",
    "react-intersection-observer": "^9.5.3",
    "react-multi-carousel": "^2.8.4",
    "react-paginate": "^8.2.0",
    "react-player": "^2.14.1",
    "react-router-dom": "^6.15.0",
    "react-scroll": "^1.9.0",
    "react-toastify": "^9.1.3",
    "react-visibility-sensor": "^5.1.1",
    "sass": "^1.66.1",
    "swiper": "^10.3.1"
  },
  "devDependencies": {
    "@types/react": "^18.2.15",
    "@types/react-dom": "^18.2.7",
    "@vitejs/plugin-react": "^4.0.3",
    "eslint": "^8.45.0",
    "eslint-plugin-react": "^7.32.2",
    "eslint-plugin-react-hooks": "^4.6.0",
    "eslint-plugin-react-refresh": "^0.4.3",
    "sass": "^1.66.1",
    "vite": "^5.0.12"
  }
}

**Comment by MatthewPattell** [comment]
You need little bit change config for remove typescript.

Vite config (configure SsrBoost plugin)
```
    SsrBoost({
      tsconfigAliases: false, // disable tsconfig aliases
      serverFile: 'server.js',
      clientFile: 'client.js'
    }),
```

index.html (replace client.ts on client.js)
```
<script type="module" src="/client.js" async></script>
```
