### ISSUE TITLE
Any plans to support Bun?

### ISSUE THREAD

**Issue by marviobezerra** [Lomray-Software/vite-ssr-boost#14]
First of all, I really enjoy this project. Great job! I've been using Bun in all my new projects. Any plans to support it?

**Comment by MatthewPattell** [comment]
@marviobezerra Hi. Thank you!
I already have task on board https://github.com/orgs/Lomray-Software/projects/2?pane=issue&itemId=46215934 and this is good feature to support another solutions like bun or fastify etc. 

But it all comes down to time, which is something we don’t have much of. Tasks like this require a significant amount of time. To do something well, you need to immerse yourself in the business problem, see it from the inside, and then you can deliver exactly what is expected. Unfortunately, at the moment, I don’t have any projects on hand using Bun or something similar.

However, I hope that such a project will come up soon, and I’ll be able to take on the implementation of this task. And of course, I’m always open to PRs.

**Comment by marviobezerra** [comment]
I don't have access to the board =/

As an update, I managed to run the project using bun. Using `bun --bun` according to Bun's documentation you can run and build Vite applications. 

```
bun --bun ssr-boost dev
bun --bun ssr-boost build
``` 

After building, I can run the application using the same flag.

```
bun --bun ssr-boost start --host --build-dir .
```

This approach has a few drawbacks. For example, you cannot use bun's built in methods.

I forked the repo and I'll try to play around... No promises at this point.

**Comment by marviobezerra** [comment]
Any tips on how to run in development mode?

**Comment by MatthewPattell** [comment]
1. Clone repo
2. Open `rollup.config.js`
3. Make changes:
```
// const dest = 'lib';
// here you sample repo with installed vite-ssr-boost
const dest = '../vite-template/node_modules/@lomray/vite-ssr-boost';
```
4. Run `npm run build:watch`
5. Make changes in `vite-ssr-boost`
6. Test it in `vite-template` (for example)
