### ISSUE TITLE
Support for Fastify and other HTTP frameworks

### ISSUE THREAD

**Issue by giacomorebonato** [Lomray-Software/vite-ssr-boost#2]
Express is arguably unmaintained and there are many alternatives that are used.
The same HTTP server can be used for building API end points.

**Comment by MatthewPattell** [comment]
@giacomorebonato Thank you for your suggestion! We are indeed considering the possibility of adding support for various HTTP frameworks, [such as Fastify](https://github.com/orgs/Lomray-Software/projects/2?pane=issue&itemId=46215934). As you've pointed out, Express may become outdated for some projects, and we aim to provide a more versatile solution.
