### ISSUE TITLE
[SUGGESTION] Add a quick section on SSR development and deployment to the README

### ISSUE THREAD

**Issue by YPCrumble** [Lomray-Software/vite-ssr-boost#6]
Thanks for creating this! 

I've been looking for a Vite plugin that lets me use React Router out of the box without having to change my whole routing system (e.g., NextJS, or even Remix.run). One thing I don't understand from the README is how this works with my Express server, both if I want to test SSR locally and if I want to deploy. I'd love to see a really simple Express setup in the README. Hoping the suggestion is helpful, and thank you again for creating this repo!

**Comment by MatthewPattell** [comment]
@YPCrumble [Have you seen the demo application yet?](https://github.com/Lomray-Software/vite-template). It shows how this framework works, as well as how to deploy.

**Comment by YPCrumble** [comment]
@MatthewPattell thanks for your response! I did and searched "express" and didn't see anything - but your suggestion helped me figure it out. It appears the Express server is in this repo at `src/node/server.ts` and everything is done via the Dockerfile. Closing this issue.

**Comment by MatthewPattell** [comment]
@YPCrumble [Please also note that you have access to Express at any stage of the request](https://github.com/Lomray-Software/vite-template/blob/prod/src/server.ts#L31)
