### ISSUE TITLE
Is there a way to implement code splitting with this repo?

### ISSUE THREAD

**Issue by YPCrumble** [Lomray-Software/vite-ssr-boost#7]
Have you been able to implement code splitting with this repo? I've been using loadable components which works great with Webpack but [doesn't support Vite](https://github.com/vitejs/vite/discussions/2721#discussioncomment-6497045).

**Comment by MatthewPattell** [comment]
@YPCrumble You don't need any external lib for code-splitting. [You have to use dynamic import for your routes](https://github.com/Lomray-Software/vite-template/blob/prod/src/routes/index.ts#L30) and you can use [React.lazy + Suspense](https://github.com/Lomray-Software/vite-template/blob/prod/src/pages/not-lazy/index.tsx#L9) for components.

**Comment by YPCrumble** [comment]
Thank you for your response! Does this mean that Vite / this library automatically creates different bundles depending on the route and adjusts the `<head/>` elements accordingly with only the code necessary for a specific route? Is that done by Vite or by this library? 

I looked into the codebase and can't figure out how this is actually working to update where the JS bundle gets delivered into the `<head/>` element.

Thanks again for your response!

**Comment by MatthewPattell** [comment]
This library does not manage code-splitting. If you really want to understand how this works, perhaps you should take a look at the [Vite](https://vitejs.dev/guide/features#async-chunk-loading-optimization) and [Rollup](https://rollupjs.org/tutorial/#code-splitting) documentation.

**Comment by YPCrumble** [comment]
Thanks, super helpful, closing this.
