### ISSUE TITLE
TypeError [ERR_UNKNOWN_FILE_EXTENSION]: Unknown file extension ".css"

### ISSUE THREAD

**Issue by chrisidakwo** [Lomray-Software/vite-ssr-boost#9]
**Describe the bug**
I'm not that experienced with these things yet, but the app runs as should until I add the recommended providers from @adobe/react-spectrum package and then it crashes with the error message in the screenshot. I suspect it has more to do with the SSR implementation from this package (it fails in the server.ts. file). I've used @adobe/react-spectrum in other React Vite projects and never ran into this issue.

**To Reproduce**
1. Setup a new project using [the vite-template example](https://github.com/Lomray-Software/vite-template) 
2. Install @adobe/react-spectrum and react-aria
3. Wrap children with @adobe/react-spectrum Provider and I18nProvider as recommended (https://react-spectrum.adobe.com/react-aria/ssr.html, https://react-spectrum.adobe.com/react-spectrum/Provider.html)
4. Run `npm run dev`
5. It fails with the error message in the screenshot below

**Expected behavior**
Vite should not have an issue processing CSS files from vendor

**Screenshots**

<img width="1919" alt="Screenshot 2023-12-31 at 05 24 25" src="https://github.com/Lomray-Software/vite-ssr-boost/assets/29854560/ecc58243-91d1-47bb-8853-7021e3a8a176">

<img width="1419" alt="Screenshot 2023-12-31 at 05 27 55" src="https://github.com/Lomray-Software/vite-ssr-boost/assets/29854560/a205de7b-506f-4e0c-9967-e0605afa2457">

**Desktop (please complete the following information):**
 - OS: Mac OS
 - Browser Chrome

**Comment by MatthewPattell** [comment]
@chrisidakwo Hi, check [this please](https://github.com/adobe/react-spectrum/issues/5401#issuecomment-1815445715)

Short summary:
1.
```
 <ConsistentSuspenseProvider>
      <StoreManagerProvider storeManager={storeManager}>
        <MetaManagerProvider manager={metaManager}>
          <Suspense fallback={<Fallback />}>
            <I18nProvider locale="en-GB">
              <Provider theme={defaultTheme}>{children}</Provider>
            </I18nProvider>
          </Suspense>
        </MetaManagerProvider>
      </StoreManagerProvider>
    </ConsistentSuspenseProvider>
```
2.
```
// vite.config.ts

export default defineConfig({
  root: 'src',
  publicDir: '../public',
  envDir: '../',
  build: {
    outDir: '../build',
  },
  ssr: {
    noExternal: [
      '@adobe/react-spectrum',
      '@react-spectrum/actionbar',
      '@react-spectrum/actiongroup',
      '@react-spectrum/avatar',
      '@react-spectrum/badge',
      '@react-spectrum/breadcrumbs',
      '@react-spectrum/button',
      '@react-spectrum/buttongroup',
      '@react-spectrum/calendar',
      '@react-spectrum/checkbox',
      '@react-spectrum/combobox',
      '@react-spectrum/contextualhelp',
      '@react-spectrum/datepicker',
      '@react-spectrum/dialog',
      '@react-spectrum/divider',
      '@react-spectrum/dnd',
      '@react-spectrum/form',
      '@react-spectrum/icon',
      '@react-spectrum/illustratedmessage',
      '@react-spectrum/inlinealert',
      '@react-spectrum/image',
      '@react-spectrum/label',
      '@react-spectrum/labeledvalue',
      '@react-spectrum/layout',
      '@react-spectrum/link',
      '@react-spectrum/list',
      '@react-spectrum/listbox',
      '@react-spectrum/menu',
      '@react-spectrum/meter',
      '@react-spectrum/numberfield',
      '@react-spectrum/overlays',
      '@react-spectrum/picker',
      '@react-spectrum/progress',
      '@react-spectrum/provider',
      '@react-spectrum/radio',
      '@react-spectrum/slider',
      '@react-spectrum/searchfield',
      '@react-spectrum/statuslight',
      '@react-spectrum/switch',
      '@react-spectrum/table',
      '@react-spectrum/tabs',
      '@react-spectrum/tag',
      '@react-spectrum/text',
      '@react-spectrum/textfield',
      '@react-spectrum/theme-dark',
      '@react-spectrum/theme-default',
      '@react-spectrum/theme-light',
      '@react-spectrum/tooltip',
      '@react-spectrum/view',
      '@react-spectrum/well',
      '@spectrum-icons/illustrations',
      '@spectrum-icons/ui',
      '@spectrum-icons/workflow'
    ],
  },
  plugins: [SsrBoost(), react(), MobxManager()],
});

```

**Comment by chrisidakwo** [comment]
Great, thanks!

I actually switched from react-spectrum to MUI and the issue was gone. Became obvious it had something to do with react-spectrum but wanted to wait for your response.

Anyway, thanks.

**Comment by chrisidakwo** [comment]
Great, thanks!

I actually switched from react-spectrum to MUI and the issue was gone. Became obvious it had something to do with react-spectrum but wanted to wait for your response.

Anyway, thanks.
